#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate GP-180 module/effect documentation folders (RU)."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "docs" / "modules"

# id, slug, name_ru, type, description_ru, params_ru, usage_variants (list of dicts)
MODULES = {
    "01-nr": {
        "title": "NR — Noise Gate (шумодав)",
        "chain": "Первый модуль цепи по умолчанию. Режет шумы до усиления.",
        "effects": [
            ("gate-1", "Gate 1", "Gate",
             "Простой шумодав: сигнал ниже порога глушится.",
             ["Threshold — порог срабатывания", "Decay — скорость затухания шума"],
             [("Ритм с дисторшеном", "Threshold 40–55, Decay короткий — чёткие паузы между риффами."),
              ("Лид с сустейном", "Threshold ниже, Decay длиннее — не обрезать хвост ноты.")]),
            ("gate-2", "Gate 2", "Gate",
             "Гибкий шумодав с атакой и релизом.",
             ["Threshold", "Attack — как быстро открывается", "Release — как быстро гасит шум"],
             [("Метал с палм-мьютом", "Attack короткий, Release средний."),
              ("Динамичная чистая игра", "Attack длиннее, Threshold мягче.")]),
            ("gate-3", "Gate 3", "Gate",
             "Inverse Expander: убирает шум, сохраняя сустейн и динамику.",
             ["Threshold", "Attack", "Release", "Hold — удержание открытого состояния"],
             [("High-gain SnapTone/NAM", "Gate 3 перед N→S: Threshold по шуму усилителя, Hold 20–40."),
              ("Акустика / мандолина", "Мягкий Threshold; не зажимать тихие атаки.")]),
        ],
    },
    "02-pre": {
        "title": "PRE — Pre-Effects (пре-эффекты)",
        "chain": "Перед вау и дисторшеном: компрессия, бусты, фильтры, питч, симуляторы.",
        "effects": [
            ("comp", "COMP", "Comp",
             "Компрессор в духе Ross™: мягкое натуральное сжатие.",
             ["Sustain", "Volume"],
             [("Мандокастер — выровнять атаки", "Sustain 35–50, Volume чуть выше unity."),
              ("Чистый кантри-ритм", "Sustain умеренный, сохранить динамику.")]),
            ("comp4", "COMP4", "Comp",
             "Студийный 4-рычажный компрессор (Keeley® C4*). Иерархия и яркий верх.",
             ["Sustain", "Attack", "Volume", "Clipping"],
             [("Соло поверх микса", "Быстрый Attack, Sustain 50–70."),
              ("Бас / низ мандолины", "Мягкий Attack, Clipping не задирать.")]),
            ("micro-boost", "Micro Boost", "Boost",
             "Чистый буст до +20 дБ без смены характера (MXR® Micro Amp*).",
             ["Gain"],
             [("Push amp into OD", "Gain 30–50 перед ламповым AMP."),
              ("Соло-буст", "CTRL на Micro Boost, Gain 40–60.")]),
            ("b-boost", "B-Boost", "Boost",
             "Плотный кремовый буст/овердрайв (Xotic® BB Preamp*).",
             ["Gain", "Volume", "Bass", "Treble"],
             [("Тёплый буст под clean amp", "Gain низкий, Bass чуть вверх."),
              ("Густой ритм", "Gain средний, Treble слегка вниз.")]),
            ("14-boost", "14 Boost", "Boost",
             "Агрессивный tight-буст (Fortin® Grind*): +20 дБ, низкий шум.",
             ["Gain"],
             [("Modern metal", "Перед high-gain AMP/NAM."),
              ("Подтянуть драйв", "Gain 20–35.")]),
            ("boost", "Boost", "Boost",
             "EP-style буст: сильный низ, яркий верх (Xotic® EP Booster*).",
             ["Gain", "+3dB", "Bright"],
             [("Vintage lift", "Bright OFF, +3dB ON."),
              ("Flat modern", "Bright ON.")]),
            ("od-9", "OD 9", "Overdrive",
             "TS9-стиль: прозрачный буст преампа, кранч-ритм.",
             ["Gain", "Tone", "Volume"],
             [("Перед Marshall/UK", "Gain 30–45, Tone 45–55."),
              ("Мандолина в миксе", "Gain низкий как mid-boost ~700–900 Гц.")]),
            ("yellow-od", "Yellow OD", "Overdrive",
             "Асимметричный овердрайв 70-х: звук близок к исходному.",
             ["Gain", "Volume"],
             [("Блюз", "Gain средний, Volume по месту в миксе.")]),
            ("penesas", "Penesas", "Overdrive",
             "Klon® Centaur*-стиль: amp-in-a-box; Gain=0 → clean boost.",
             ["Gain", "Tone", "Volume"],
             [("Clean boost", "Gain 0–15."),
              ("Соло поверх бэнда", "Gain 25–40, Tone под площадку.")]),
            ("super-od", "Super OD", "Overdrive",
             "Тёплый асимметричный овердрайв.",
             ["Gain", "Tone", "Volume"],
             [("Мягкий кранч", "Gain 25–40.")]),
            ("blues-od", "Blues OD", "Overdrive",
             "Выразительный OD от тёплого до открытого дисторшена.",
             ["Gain", "Tone", "Volume"],
             [("Динамика от Volume гитары", "Gain средний, играть от ручки громкости.")]),
            ("t-wah", "T-Wah", "Filter",
             "Touch wah / envelope filter: реагирует на силу игры.",
             ["Sens", "Range", "Q", "Mix", "Mode Guitar/Bass"],
             [("Фанк", "Sens под атаку, Mode Guitar."),
              ("Мандолина chop", "Sens умеренный, Mix 40–60 — не размывать атаку.")]),
            ("a-wah", "A-Wah", "Auto Filter",
             "Авто-вау с заданной скоростью.",
             ["Depth", "Rate", "Volume", "Low", "High", "Q", "Sync"],
             [("Псих/фанк ритм", "Sync ON к темпу дромов.")]),
            ("step-filter", "Step Filter", "Filter",
             "4-шаговый автофильтр — синтоподобные тембры.",
             ["Step 1–4", "Rate", "Sync"],
             [("Электронные текстуры", "Sync к BPM, яркие Step-контрасты.")]),
            ("octa", "OCTA", "Pitch",
             "Полифонический октавер.",
             ["Low Oct", "High Oct", "Dry"],
             [("Толщина лида", "Low Oct 30–50, Dry высоко."),
              ("Мандолина «басовее»", "Только Low Oct чуть-чуть.")]),
            ("pitch", "Pitch", "Pitch",
             "Полифонический питч-шифтер / гармонайзер.",
             ["Low/Hi Pitch", "Dry", "Low/Hi Vol"],
             [("Гармонии в терцию/квинту", "Hi Pitch +3 / +4 / +7 semitones.")]),
            ("p-bend", "P-Bend", "Pitch",
             "Полифонический bend/harmony с диапазоном.",
             ["Low/Hi Pitch", "Wet", "Dry", "Range"],
             [("Pedal steel-like", "Назначить на EXP.")]),
            ("hammy", "Hammy", "Pitch",
             "Whammy®*-стиль (моно). Position → EXP.",
             ["Range", "Harmony", "Volume", "Position"],
             [("Dive bomb / octave up", "EXP на Position.")]),
            ("ring-mod", "Ring Mod", "Special",
             "Кольцевой модулятор: колокола, металлические тембры.",
             ["Mix", "Freq", "Fine", "Tone"],
             [("Эксцентричные партии", "Mix низкий, Freq подобрать к тональности.")]),
            ("saturate", "Saturate", "Special",
             "Ленточная сатурация: аналоговая теплота.",
             ["Mix", "Volume", "High Cut"],
             [("Склеить цифровой clean", "Mix 20–40, High Cut чуть вниз."),
              ("Мандокастер warmer", "Лёгкая сатурация вместо жёсткого OD.")]),
            ("ac-sim", "AC Sim", "Simulator",
             "Симулятор акустики (Standard/Jumbo/Enhanced/Piezo).",
             ["Body", "Top", "Volume", "Mode"],
             [("Электрика → акустика", "Mode Standard/Jumbo."),
              ("Мандолина acoustic-ish", "Body умеренно, Top не задирать — магниты и так яркие.")]),
            ("h-to-s", "H to S", "Simulator",
             "Симулятор: хамбакер → сингл (ST bridge).",
             ["Volume", "Tone"],
             [("Сделать ярче и острее", "Tone подобрать под микс.")]),
            ("s-to-h", "S to H", "Simulator",
             "Симулятор: сингл → хамбакер (LP bridge).",
             ["Volume", "Tone"],
             [("Утолстить мандокастер", "Полезно при тонком магнитном датчике.")]),
        ],
    },
    "03-wah": {
        "title": "WAH — Wah / педаль управления",
        "chain": "Вау и whammy. Для EXP: назначить Position, включить модуль.",
        "effects": [
            ("v-wah", "V-Wah", "Wah",
             "VOX® V846*-стиль: эмоциональный вау в СЧ–ВЧ.",
             ["Range", "Q", "Volume", "Position (EXP)"],
             [("Соло с вау", "Q средний; Range не слишком узкий.")]),
            ("c-wah", "C-Wah", "Wah",
             "Альтернативный вокально-выразительный вау.",
             ["Range", "Q", "Volume"],
             [("Ритм funk", "Открытый Range.")]),
            ("b-wah", "B-Wah", "Wah",
             "Вау, заточенный под бас.",
             ["Range", "Q", "Volume"],
             [("Бас фанк", "Range сместить ниже.")]),
            ("hammy-wah", "Hammy", "Pitch",
             "Whammy в слоте WAH (удобно на EXP).",
             ["Range", "Harmony", "Volume", "Position"],
             [("Live pitch FX", "Harmony ON для слоёв.")]),
        ],
    },
    "04-dst": {
        "title": "DST — Distortion / Overdrive",
        "chain": "Драйв до SnapTone/AMP. Часто как mid-boost или основной dirt.",
        "effects": [
            ("green-od", "Green OD", "OD", "TS808*-стиль: тёплый, деликатный OD/буст.",
             ["Gain", "Tone", "Volume"],
             [("Перед brit amp", "Классика."), ("Мандолина mid push", "Gain низкий.")]),
            ("od-9-dst", "OD 9", "OD", "TS9: прозрачный push преампа.",
             ["Gain", "Tone", "Volume"], [("Crunch rhythm", "Gain 40–60.")]),
            ("yellow-od-dst", "Yellow OD", "OD", "Асимметричный OD 70-х.",
             ["Gain", "Volume"], [("Vintage rock", "")]),
            ("penesas-dst", "Penesas", "OD", "Klon*-стиль amp-in-a-box.",
             ["Gain", "Tone", "Volume"], [("Clean boost → mild OD", "")]),
            ("super-od-dst", "Super OD", "OD", "Тёплый асимметричный OD.",
             ["Gain", "Tone", "Volume"], [("Мягкий кранч", "")]),
            ("scream-od", "Scream OD", "OD", "TS-семейство с Fat.",
             ["Gain", "Volume", "Tone", "Fat"], [("Fat ON для толщины", "")]),
            ("blues-od-dst", "Blues OD", "OD", "Выразительный blues/rock OD.",
             ["Gain", "Tone", "Volume"], [("Touch sensitive", "")]),
            ("force", "Force", "OD", "Fulltone® OCD*: трубный отклик, HP/LP.",
             ["Gain", "Tone", "Volume", "Mode HP/LP"],
             [("LP — сохранить исходный тон", "HP — больше низа и drive.")]),
            ("tube-clipper", "Tube Clipper", "OD", "OD на 12AX7: мягкий сустейн.",
             ["Gain", "VOL", "Bass", "Treble"], [("Violin-like sustain", "")]),
            ("taichi-od", "TaiChi OD", "OD", "Zendrive®*-характер: ламповость, touch.",
             ["Gain", "Tone", "Volume", "Voice"], [("Динамичный OD", "")]),
            ("lazaro", "Lazaro", "Fuzz", "Big Muff®*: плотная стена фузза.",
             ["Sustain", "Tone", "Volume"], [("Дроны / стена", "Не для ритм-гитары в плотном миксе.")]),
            ("red-haze", "Red Haze", "Fuzz", "Fuzz Face®*: тяжёлый, острый.",
             ["Fuzz", "Volume"], [("Classic rock fuzz", "Играть от Volume гитары.")]),
            ("plustortion", "Plustortion", "Dist", "MXR® Distortion+*: germanium soft clip.",
             ["Gain", "Volume"], [("Hard rock 80s", "")]),
            ("sm-dist", "SM Dist", "Dist", "Оранжевый 3-ручечный дист 70–80-х.",
             ["Gain", "Tone", "Volume"], [("Классический рок", "")]),
            ("darktale", "Darktale", "Dist", "ProCo™ Rat* (LM308).",
             ["Gain", "Filter", "Volume"], [("От гейта до фузза", "Filter против часовой стрелки = ярче.")]),
            ("chief", "Chief", "Dist", "Guv'nor*-стиль marshall-in-a-box + 3-band.",
             ["Gain", "Volume", "Bass", "Middle", "Treble"], [("UK crunch box", "")]),
            ("la-charger", "La Charger", "Dist", "Британский дист с Tone.",
             ["Gain", "Tone", "Volume"], [("Riff rock", "")]),
            ("flagman-dist", "Flagman Dist", "Dist", "Modern UK high-gain dirt box.",
             ["Gain", "Volume", "Bass", "Treble", "Presence", "Tight"],
             [("Tight metal boost", "Tight вверх.")]),
            ("flex-od", "Flex OD", "Bass OD", "Простой OD для гитары/баса, Blend.",
             ["Gain", "Tone", "Volume", "Mode", "Blend"],
             [("Бас с характером", "Blend 40–60 сохранить фундамент.")]),
            ("bass-od", "Bass OD", "Bass OD", "Басовый OD с сохранением динамики.",
             ["Gain", "Blend", "Volume", "Bass", "Treble"], [("Bass drive", "")]),
            ("black-bass", "Black Bass", "Bass Pre", "Darkglass® B7K*-стиль.",
             ["Gain", "Blend", "Volume", "Low/Lo-mid/Hi-mid/Treble", "Attack"],
             [("Modern bass DI", "")]),
            ("bass-hammer", "Bass Hammer", "Bass Pre", "Aguilar® Tone Hammer*-стиль.",
             ["Gain", "Master", "Bass", "Middle", "Treble", "Mid Freq", "Drive"],
             [("Шейпинг баса", "Mid Freq sweep.")]),
            ("micro-boost-dst", "Micro Boost", "Boost", "Чистый буст в слоте DST.",
             ["Gain"], [("Соло push", "")]),
            ("b-boost-dst", "B-Boost", "Boost", "BB-style в DST.",
             ["Gain", "Volume", "Bass", "Treble"], [("Толстый буст", "")]),
            ("14-boost-dst", "14 Boost", "Boost", "Grind-style tight boost.",
             ["Gain"], [("Перед high-gain", "")]),
            ("boost-dst", "Boost", "Boost", "EP-style boost.",
             ["Gain", "+3dB", "Bright"], [("Vintage lift", "")]),
        ],
    },
    "05-ns": {
        "title": "N→S — SnapTone (NAM)",
        "chain": "Загрузка SnapTone (конвертированных NAM). Часто вместо AMP или вместе (осторожно с DSP).",
        "effects": [
            ("empty-1-50", "Empty 1–50 (+user)", "SnapTone",
             "Слоты SnapTone: заводские 50 + пользовательмые до 100 через Valeton Suite. Параметры как у amp-блока.",
             ["Gain", "VOL", "Bass", "Middle", "Treble", "Presence"],
             [("Только SnapTone + CAB/IR", "AMP OFF, CAB ON или User IR."),
              ("SnapTone без кабинета", "Если модель already includes cab — CAB OFF."),
              ("Мандолина", "Выбирать open clean/edge-of-breakup, Gain низкий, Presence аккуратно.")]),
        ],
    },
    "06-amp": {
        "title": "AMP — симуляции усилителей",
        "chain": "Ламповые/твердотельные усилители. Gain = pre, Volume = post.",
        "effects": [
            ("tweedy", "Tweedy", "Clean/OD", "Fender® Tweed Deluxe*: от clean до wild OD.",
             ["Gain", "Tone", "Volume"], [("Country / rockabilly", "Мандолина: Gain низкий.")]),
            ("bellman-59n", "Bellman 59N", "Clean", "Bassman® '59 Normal.",
             ["Gain", "Presence", "Volume", "Bass", "Middle", "Treble"], [("Тёплый американский clean", "")]),
            ("bellman-59b", "Bellman 59B", "OD", "Bassman® '59 Bright.",
             ["Gain", "Presence", "Volume", "EQ"], [("Яркий кранч", "")]),
            ("dark-twin", "Dark Twin", "Clean", "Twin Reverb® '65.",
             ["Gain", "Volume", "EQ", "Bright"], [("Jazz/country clean", "Мандокастер: Bright OFF, Treble ↓.")]),
            ("silver-twin", "Silver Twin", "Clean", "Silverface Twin.",
             ["Gain", "Volume", "Bass", "Treble"], [("Исторический clean", "")]),
            ("supdual-cl", "SUPDual CL", "Clean", "Supro® Dual Tone clean.",
             ["Gain", "Volume", "Tone"], [("Fat compressed clean", "")]),
            ("supdual-od", "SUPDual OD", "OD", "Supro Dual Tone dirty.",
             ["Gain1/2", "Tone1/2", "Volume"], [("Артикулированный grind", "")]),
            ("foxy-30n", "Foxy 30N", "Clean", "VOX® AC30 Normal.",
             ["Gain", "Volume", "Tone cut", "Bright"], [("Британский chime", "Мандолина: Tone cut по часовой = темнее.")]),
            ("foxy-30tb", "Foxy 30TB", "OD", "AC30 Top Boost.",
             ["Gain", "Tone cut", "Volume", "Bass", "Treble", "Char Cool/Hot"], [("Brit Invasion OD", "")]),
            ("j-120-cl", "J-120 CL", "Clean", "Jazz Chorus solid-state.",
             ["Gain", "Bright", "EQ"], [("Чистый джаз/pop", "Хорошо для мандолины без «ламповой грязи».")]),
            ("match-cl", "Match CL", "Clean", "Matchless™ Chieftain clean.",
             ["Gain", "Presence", "Volume", "EQ"], [("Boutique clean", "")]),
            ("match-od", "Match OD", "OD", "Chieftain OD.",
             ["Gain", "Presence", "Volume", "EQ"], [("Dynamic boutique drive", "")]),
            ("l-star-cl", "L-Star CL", "Clean", "Mesa Lone Star® CH1.",
             ["Gain", "Presence", "Volume", "EQ"], [("Живой mid-forward clean", "")]),
            ("l-star-od", "L-Star OD", "OD", "Lone Star CH2.",
             ["Gain", "Presence", "Volume", "EQ"], [("Expressive OD", "")]),
            ("bogsv-cl", "BogSV CL", "Clean", "Bogner® Shiva CH1.",
             ["Gain", "Presence", "Volume", "Bass", "Treble", "Bright"], [("Прозрачный modern clean", "")]),
            ("bogsv-od", "BogSV OD", "OD", "Shiva CH2.",
             ["Gain", "Presence", "Volume", "EQ"], [("Flexible OD", "")]),
            ("bog-bluev", "Bog BlueV", "OD", "Bogner XTC Blue Vintage.",
             ["Gain", "Presence", "Volume", "EQ"], [("Classic rock plexi-ish", "")]),
            ("bog-bluem", "Bog BlueM", "OD", "XTC Blue Modern.",
             ["Gain", "Presence", "Volume", "EQ"], [("Modern classic rock", "")]),
            ("bog-redv", "Bog RedV", "HiGain", "XTC Red Vintage.",
             ["Gain", "Presence", "Volume", "EQ"], [("Огненный lead", "")]),
            ("bog-redm", "Bog RedM", "HiGain", "XTC Red Modern.",
             ["Gain", "Presence", "Volume", "EQ"], [("Modern hi-gain", "")]),
            ("z38-cl", "Z38 CL", "Clean", "Dr. Z® Maz 38 clean.",
             ["Gain", "Tone cut", "Volume", "EQ"], [("Широкий отклик", "")]),
            ("z38-od", "Z38 OD", "OD", "Maz 38 OD.",
             ["Gain", "Tone cut", "Volume", "EQ"], [("US/UK hybrid", "")]),
            ("knights-cl", "Knights CL", "Clean", "Pendragon normal bright off.",
             ["Gain", "Volume", "EQ"], [("Британский clean", "")]),
            ("knights-clp", "Knights CL+", "Clean", "Pendragon bright on.",
             ["Gain", "Volume", "EQ"], [("Ярче", "")]),
            ("knights-od", "Knights OD", "OD", "Pendragon Drive.",
             ["Gain", "Volume", "EQ"], [("UK drive", "")]),
            ("bad-kt-cl", "Bad-KT CL", "Clean", "Bad Cat® Hot Cat clean.",
             ["Gain", "Presence", "Volume"], [("Class A harmonics", "")]),
            ("bad-kt-od", "Bad-KT OD", "OD", "Hot Cat OD.",
             ["Gain", "Presence", "Volume", "Edge", "Bass", "Treble"], [("Гибрид UK/US", "")]),
            ("solo100-cl", "Solo100 CL", "Clean", "Soldano® SLO clean.",
             ["Gain", "Presence", "Volume", "EQ"], [("Tight clean", "")]),
            ("solo100-od", "Solo100 OD", "OD", "SLO crunch.",
             ["Gain", "Presence", "Volume", "EQ"], [("Crunch", "")]),
            ("solo100-ld", "Solo100 LD", "HiGain", "SLO overdrive / brown sound.",
             ["Gain", "Presence", "Volume", "EQ"], [("Lead sustain", "")]),
            ("uk-45", "UK 45", "OD", "Marshall® JTM45 Normal.",
             ["Gain", "Presence", "Volume", "EQ"], [("Plexi foundation", "")]),
            ("uk-45p", "UK 45+", "OD", "JTM45 Bright.",
             ["Gain", "Presence", "Volume", "EQ"], [("Ярче plexi", "")]),
            ("uk-45jp", "UK 45JP", "OD", "JTM45 Jump.",
             ["Gain1", "Gain2", "Presence", "Volume", "EQ"], [("Jump channels", "")]),
            ("uk-50", "UK 50", "OD", "JMP50 Normal.",
             ["Gain", "Presence", "Volume", "EQ"], [("Полнее чем 45", "")]),
            ("uk-50p", "UK 50+", "OD", "JMP50 Bright.",
             ["Gain", "Presence", "Volume", "EQ"], [("Bright plexi", "")]),
            ("uk-50jp", "UK 50JP", "OD", "JMP50 Jump.",
             ["Gain1", "Gain2", "Presence", "Volume", "EQ"], [("Jump", "")]),
            ("uk-slp", "UK SLP", "OD", "1959HW Plexi.",
             ["Gain", "Presence", "Volume", "EQ"], [("Classic Marshall crunch", "")]),
            ("uk-800", "UK 800", "OD", "JCM800®.",
             ["Gain", "Presence", "Volume", "EQ"], [("80s rock/metal", "")]),
            ("uk-900", "UK 900", "HiGain", "JCM900®.",
             ["Gain", "Presence", "Volume", "EQ"], [("Versatile hi-gain", "")]),
            ("flagman-1", "Flagman 1", "OD", "Brown Eye BE channel.",
             ["Gain", "Presence", "Volume", "EQ"], [("Boutique UK", "")]),
            ("flagman-p1", "Flagman+ 1", "HiGain", "HBE channel.",
             ["Gain", "Presence", "Volume", "EQ"], [("Higher gain BE", "")]),
            ("mess2c-1", "Mess2C+ 1", "OD", "Mark IIC+ Lead var.1.",
             ["Gain", "Presence", "Volume", "EQ"], [("US metal classic", "")]),
            ("mess2c-2", "Mess2C+ 2", "OD", "Mark IIC+ var.2.",
             ["Gain", "Presence", "Volume", "EQ"], [("Alternative switch", "")]),
            ("mess2c-3", "Mess2C+ 3", "OD", "Mark IIC+ var.3.",
             ["Gain", "Presence", "Volume", "EQ"], [("Ещё вариант EQ", "")]),
            ("mess4-ld", "Mess4 LD", "HiGain", "Mark IV Lead.",
             ["Gain", "Presence", "Volume", "EQ"], [("От голоса до modern hi-gain", "")]),
            ("mess-dualv", "Mess DualV", "HiGain", "Dual Rectifier Vintage.",
             ["Gain", "Presence", "Volume", "EQ"], [("Толстый rectifier", "")]),
            ("mess-dualm", "Mess DualM", "HiGain", "Dual Rectifier Modern.",
             ["Gain", "Presence", "Volume", "EQ"], [("Современный rectifier", "")]),
            ("juice-r100", "Juice R100", "HiGain", "Orange® Rockerverb Dirty.",
             ["Gain", "Volume", "EQ"], [("Тёплый rock", "")]),
            ("ev-51", "EV 51", "HiGain", "Peavey® 5150 Lead.",
             ["Gain", "Presence", "Volume", "EQ"], [("Metal lead", "")]),
            ("eagle-120", "Eagle 120", "HiGain", "ENGL® Savage 120.",
             ["Gain", "Presence", "Volume", "EQ"], [("Punishing metal", "")]),
            ("power-ld", "Power LD", "HiGain", "ENGL Powerball II CH4.",
             ["Gain", "Presence", "Volume", "EQ"], [("Tight modern metal", "")]),
            ("dizz-vh", "Dizz VH", "HiGain", "Diezel® VH4.",
             ["Gain", "Presence", "Volume", "EQ"], [("German modern hi-gain", "")]),
            ("classic-bass", "Classic Bass", "Bass", "Ampeg® SVT*.",
             ["Gain", "Midrange freq", "Volume", "EQ"], [("Студийный бас", "")]),
            ("foxy-bass", "Foxy Bass", "Bass", "VOX AC100 bass.",
             ["Volume", "Bass", "Treble"], [("60s bass", "")]),
            ("mess-bass", "Mess Bass", "Bass", "Mesa Bass 400.",
             ["Gain", "Volume", "EQ"], [("Early album bass", "")]),
            ("mini-bass", "Mini Bass", "Bass", "Ampeg B-15 Flip Top.",
             ["Volume", "Bass", "Treble"], [("Vintage studio bass", "")]),
            ("bass-pre", "Bass Pre", "Bass", "Alembic F-2B preamp.",
             ["Volume", "Bright", "EQ"], [("Гибкий басовый пре", "")]),
            ("ac-pre", "AC Pre", "Acoustic", "AER® Colourizer 2 acoustic pre.",
             ["Volume", "Tone", "Balance", "EQ Freq/Q/Gain"],
             [("Акустика/мандолина DI", "Параметрический EQ — ключ к миксу.")]),
        ],
    },
    "07-cab": {
        "title": "CAB — кабинеты и IR",
        "chain": "После AMP/SnapTone. User IR 1–20 (1024/2048). Precision: regular/high.",
        "effects": [
            ("lux-1x12", "LUX 1x12", "Cab", "Fender Deluxe Reverb 1x12.",
             ["Volume", "Low Cut", "High Cut", "Precision"], [("Clean american", "")]),
            ("twd-lux-1x12", "TWD LUX 1x12", "Cab", "Tweed Deluxe 5E3 1x12.",
             ["Volume", "Low/High Cut", "Precision"], [("Tweed", "")]),
            ("twin-2x12", "Twin 2x12", "Cab", "Twin Reverb '65 2x12.",
             ["Volume", "Cuts", "Precision"], [("Открытый clean", "Мандолина: High Cut 8–10 kHz.")]),
            ("bellman-4x10", "Bellman 4x10", "Cab", "Bassman '59 4x10.",
             ["Volume", "Cuts", "Precision"], [("Толстый US", "")]),
            ("foxy-1x12", "Foxy 1x12", "Cab", "VOX AC15 1x12.",
             ["Volume", "Cuts", "Precision"], [("Brit small", "")]),
            ("foxy-2x12", "Foxy 2x12", "Cab", "VOX AC30 2x12.",
             ["Volume", "Cuts", "Precision"], [("Chime", "")]),
            ("uk-2x12", "UK 2x12", "Cab", "Marshall 1936 2x12.",
             ["Volume", "Cuts", "Precision"], [("Studio UK", "")]),
            ("uk-vintage-4x12", "UK Vintage 4x12", "Cab", "Marshall 1982B 4x12.",
             ["Volume", "Cuts", "Precision"], [("Vintage 4x12", "")]),
            ("uk-basket-4x12", "UK Basket 4x12", "Cab", "Basketweave 1975 4x12.",
             ["Volume", "Cuts", "Precision"], [("Classic weave", "")]),
            ("uk-30-4x12", "UK 30 4x12", "Cab", "Marshall 1960A 4x12.",
             ["Volume", "Cuts", "Precision"], [("Standard rock cab", "")]),
            ("rev-2x12", "REV 2x12", "Cab", "Revv 2x12.",
             ["Volume", "Cuts", "Precision"], [("Modern", "")]),
            ("j-120-2x12", "J-120 2x12", "Cab", "Jazz Chorus 2x12.",
             ["Volume", "Cuts", "Precision"], [("JC clean", "")]),
            ("bog-2x12", "Bog 2x12", "Cab", "Bogner 2x12 G12M.",
             ["Volume", "Cuts", "Precision"], [("Boutique", "")]),
            ("bog-4x12", "Bog 4x12", "Cab", "Bogner 4x12 V30.",
             ["Volume", "Cuts", "Precision"], [("V30 rock", "")]),
            ("l-star-2x12", "L-Star 2x12", "Cab", "Mesa Lonestar 2x12.",
             ["Volume", "Cuts", "Precision"], [("Mesa", "")]),
            ("mess-4x12", "Mess 4x12", "Cab", "Mesa OS 4x12.",
             ["Volume", "Cuts", "Precision"], [("Recto/Mark", "")]),
            ("dizz-4x12", "Dizz 4x12", "Cab", "Diezel 4x12.",
             ["Volume", "Cuts", "Precision"], [("German", "")]),
            ("eagle-4x12", "Eagle 4x12", "Cab", "ENGL 4x12.",
             ["Volume", "Cuts", "Precision"], [("ENGL", "")]),
            ("flagman-4x12", "Flagman 4x12", "Cab", "Brown Eye 4x12 V30.",
             ["Volume", "Cuts", "Precision"], [("Boutique UK", "")]),
            ("solo-4x12", "Solo 4x12", "Cab", "Soldano 4x12.",
             ["Volume", "Cuts", "Precision"], [("SLO", "")]),
            ("juice-4x12", "Juice 4x12", "Cab", "Orange PPC412.",
             ["Volume", "Cuts", "Precision"], [("Orange", "")]),
            ("bellman-2x12", "Bellman 2x12", "Cab", "Bassman '67 2x12.",
             ["Volume", "Cuts", "Precision"], [("US 2x12", "")]),
            ("ampg-2x12", "AMPG 2x12", "Bass Cab", "Ampeg SVT 2x12.",
             ["Volume", "Cuts", "Precision"], [("Bass", "")]),
            ("ampg-4x10", "AMPG 4x10", "Bass Cab", "Ampeg SVT 4x10.",
             ["Volume", "Cuts", "Precision"], [("Bass", "")]),
            ("ampg-8x10", "AMPG 8x10", "Bass Cab", "Ampeg Classic 8x10.",
             ["Volume", "Cuts", "Precision"], [("Big bass", "")]),
            ("matt-2x12", "MATT 2x12", "Bass Cab", "Markbass NY 2x12.",
             ["Volume", "Cuts", "Precision"], [("Bass modern", "")]),
            ("matt-2x10", "MATT 2x10", "Bass Cab", "Markbass 2x10.",
             ["Volume", "Cuts", "Precision"], [("Bass", "")]),
            ("tracy-4x10", "Tracy 4x10", "Bass Cab", "Trace Elliot 4x10.",
             ["Volume", "Cuts", "Precision"], [("Bass", "")]),
            ("mess-bs-1x12", "Mess BS 1x12", "Bass Cab", "Mesa Subway Lite 1x12.",
             ["Volume", "Cuts", "Precision"], [("Bass", "")]),
            ("mess-bs-2x10", "Mess BS 2x10", "Bass Cab", "Mesa Subway Lite 2x10.",
             ["Volume", "Cuts", "Precision"], [("Bass", "")]),
            ("ac", "AC", "Acoustic", "Dreadnought sim.",
             ["Volume", "Cuts", "Precision"], [("Акустика", "")]),
            ("om", "OM", "Acoustic", "OM acoustic sim.",
             ["Volume", "Cuts", "Precision"], [("OM", "")]),
            ("jumbo", "JUMBO", "Acoustic", "Jumbo sim.",
             ["Volume", "Cuts", "Precision"], [("Jumbo", "")]),
            ("bird", "Bird", "Acoustic", "H-Bird acoustic.",
             ["Volume", "Cuts", "Precision"], [("Иконическая акустика", "")]),
            ("ga", "GA", "Acoustic", "GA acoustic.",
             ["Volume", "Cuts", "Precision"], [("GA", "")]),
            ("user-ir", "User IR 1–20", "User IR", "Сторонние IR 1024/2048 точек.",
             ["Volume", "Low Cut", "High Cut", "Precision"],
             [("Свой кабинет", "Загрузка через Valeton Suite."),
              ("Мандолина", "IR открытых/прозрачных 1x12 или студийных DI-friendly.")]),
        ],
    },
    "08-eq": {
        "title": "EQ — эквалайзеры",
        "chain": "Обычно после AMP/CAB. Критичен для посадки в микс (бас / ритм / вокал / ударные).",
        "effects": [
            ("guitar-eq-1", "Guitar EQ 1", "EQ",
             "Гитарный 5-полосный: 125 / 400 / 800 / 1.6k / 4k Гц.",
             ["Band1–5", "Volume"],
             [("Ритм в миксе", "↑800 Гц чуть, ↓125–250 зона баса, ↓4k если скрежет."),
              ("Мандокастер", "↓125–400 от гула датчика, ↑1.6k атака, ↓4k резкость.")]),
            ("guitar-eq-2", "Guitar EQ 2", "EQ",
             "Гитарный 5-полосный: 100 / 500 / 1k / 3k / 6k Гц.",
             ["Band1–5", "Volume"],
             [("Шире по верху", "6k — воздух/шипение; резать под вокал."),
              ("Соло cut-through", "↑1k–3k аккуратно.")]),
            ("bass-eq-1", "Bass EQ 1", "EQ",
             "Басовый: 33 / 150 / 600 / 2k / 8k Гц.",
             ["Band1–5", "Volume"],
             [("Фундамент без грязи", "33–150 под стиль, 600 punch.")]),
            ("mess-eq", "Mess EQ", "EQ",
             "5-полосный Mesa V-shape: 80 / 240 / 750 / 2.2k / 6.6k.",
             ["Band1–5"],
             [("Классический V", "↑80 и 6.6k, ↓750 — scoopy metal."),
              ("В плотном миксе", "Не уходить в крайний scoop — съест гитару под вокалом.")]),
        ],
    },
    "09-mod": {
        "title": "MOD — модуляция",
        "chain": "После EQ. Chorus/flanger/phaser/trem/detune/swell/freeze.",
        "effects": [
            ("g-chorus", "G-Chorus", "Chorus", "Винтажный ensemble-chorus конца 70-х.",
             ["Depth", "Rate", "Volume", "Sync"], [("Clean shimmer", "Мандолина: Depth небольшой.")]),
            ("c-chorus", "C-Chorus", "Chorus", "4-режимный stereo chorus.",
             ["Mode"], [("Богатый stereo", "")]),
            ("b-chorus", "B-Chorus", "Chorus/Vib", "Вариант «фиолетового» chorus.",
             ["Depth", "Rate", "Volume", "Sync"], [("Бас/низ", "")]),
            ("jet", "Jet", "Flanger", "Классический флангер.",
             ["Depth", "Rate", "Pre Delay", "Feedback", "Sync"], [("Jet whoosh", "")]),
            ("b-jet", "B-Jet", "Flanger", "Флангер для баса.",
             ["Depth", "Rate", "Pre Delay", "Feedback", "Sync"], [("Bass FX", "")]),
            ("v-roto", "V-Roto", "Vibrato", "BBD blue vibrato.",
             ["Depth", "Rate", "Sync"], [("Аналоговое вибро", "")]),
            ("vibrato", "Vibrato", "Vibrato", "Классическое вибро.",
             ["Depth", "Rate", "Volume", "Sync"], [("Широкий диапазон", "")]),
            ("o-phase", "O-Phase", "Phaser", "Phase 90*-стиль.",
             ["Rate", "Sync"], [("Eruption vibe", "")]),
            ("vibe", "Vibe", "Phaser", "Uni-Vibe: Chorus/Vibrato.",
             ["Depth", "Rate", "Volume", "Mode", "Sync"], [("Hendrix/Gilmour", "")]),
            ("o-trem", "O-Trem", "Tremolo", "Opto trem (Demeter*).",
             ["Depth", "Rate", "Sync"], [("Twin-style trem", "")]),
            ("sine-trem", "Sine Trem", "Tremolo", "Синусная форма.",
             ["Depth", "Rate", "Volume", "Sync"], [("Мягкий trem", "")]),
            ("triangle-trem", "Triangle Trem", "Tremolo", "Треугольная форма.",
             ["Depth", "Rate", "Volume", "Sync"], [("Резче", "")]),
            ("bias-trem", "Bias Trem", "Tremolo", "Bias-тремоло + Bias параметр.",
             ["Depth", "Rate", "Volume", "Sync", "Bias"], [("Винтаж amp trem", "")]),
            ("detune", "Detune", "Pitch", "Лёгкий детюн = chorus-like.",
             ["Dry", "Wet", "Detune ±50¢"],
             [("Утолщить мандолину", "Detune ±5…12¢, Wet низкий."),
              ("Дабл-трек симуляция", "Wet 30–40.")]),
            ("auto-swell", "Auto Swell", "Special", "Авто-свэлл как скрипка.",
             ["Attack", "Curve Line/Exp/Log"], [("Ambient pads", "")]),
            ("hold", "Hold", "Special", "Freeze короткого фрагмента (Activate→EXP/CTRL).",
             ["Volume", "Activate"], [("Live ambient layer", "")]),
            ("freeze", "Freeze", "Special", "Заморозка звука с Attack/Release.",
             ["Volume", "Attack", "Release", "Activate"], [("Drone under solo", "")]),
        ],
    },
    "10-dly": {
        "title": "DLY — Delay",
        "chain": "Перед ревербом. Trail сохраняет хвосты при байпасе.",
        "effects": [
            ("bbd-delay", "BBD Delay", "Delay", "Стерео аналоговый BBD-delay.",
             ["Mix", "Feedback", "Time", "Time R%", "Spread", "Level", "Sync", "Trail"],
             [("Тёплый ритм-слэп", "Time 80–140 ms.")]),
            ("digital-delay", "Digital Delay", "Delay", "Чистый стерео digital delay.",
             ["Mix", "Feedback", "Time", "Time R%", "Spread", "Level", "Sync", "Trail"],
             [("Точные повторы", "")]),
            ("pure-delay", "Pure Delay", "Delay", "Простой точный delay.",
             ["Mix", "Feedback", "Time", "Sync", "Trail"], [("Минимализм", "")]),
            ("tape-delay", "Tape Delay", "Delay", "Тейп-эхо.",
             ["Mix", "Feedback", "Time", "Sync", "Trail"], [("Винтажные хвосты", "")]),
            ("ping-pong", "Ping Pong", "Delay", "Пинг-понг L↔R.",
             ["Mix", "Feedback", "Time", "Sync", "Trail"], [("Stereo сцена", "")]),
            ("slapback", "Slapback", "Delay", "Классический слэпбэк.",
             ["Mix", "Feedback", "Time", "Trail"],
             [("Rockabilly / мандолина", "Time ~80–120 ms, Mix низкий.")]),
            ("sweep-echo", "Sweep Echo", "Delay", "Delay + sweep filter.",
             ["Mix", "Feedback", "Time", "Sweep Depth/Rate", "Syncs", "Trail"], [("Псих FX", "")]),
            ("ring-echo", "Ring Echo", "Delay", "Delay + ring mod на повторах.",
             ["Dly Mix", "Feedback", "Time", "Ring Mix", "Freq", "Tone", "Sync", "Trail"],
             [("Экспериментально", "")]),
            ("tube-delay", "Tube Delay", "Delay", "Ламповое тейп-эхо.",
             ["Mix", "Feedback", "Time", "Sync", "Trail"], [("Тёплый lead", "")]),
            ("sweet-echo", "Sweet Echo", "Delay", "Аналог 20–300 ms, тёплый.",
             ["Mix", "Feedback", "Time", "Sync", "Trail"], [("Короткий melodic echo", "")]),
            ("echo-999", "999 Echo", "Delay", "Maxon® AD900*-стиль.",
             ["Mix", "Feedback", "Time", "Sync", "Trail"], [("Органический analog", "")]),
            ("vintage-rack", "Vintage Rack", "Delay", "Рэковый delay 80-х + Mod/Tone.",
             ["Mix", "Feedback", "Time", "Mod", "Tone", "Sync", "Trail"], [("80s ambient", "")]),
            ("rev-echo", "Rev Echo", "Delay", "Реверс-повторы.",
             ["Mix", "Feedback", "Time", "Volume", "Sync", "Trail"], [("Спецэффекты", "")]),
            ("dual-echo", "Dual Echo", "Delay", "Два независимых delay A/B.",
             ["Mix/FB/Time A&B", "A/B Sync", "Trail"], [("Полиритмия повторов", "")]),
        ],
    },
    "11-rvb": {
        "title": "RVB — Reverb",
        "chain": "Конец пространственной цепи перед VOL.",
        "effects": [
            ("room", "Room", "Reverb", "Комната.",
             ["Mix", "Pre Delay", "Decay", "Trail"], [("Живая близость", "Мандолина: Mix низкий.")]),
            ("hall", "Hall", "Reverb", "Концертный зал.",
             ["Mix", "Pre Delay", "Decay", "Trail"], [("Баллады", "")]),
            ("church", "Church", "Reverb", "Церковь.",
             ["Mix", "Pre Delay", "Decay", "Trail"], [("Длинный ambience", "")]),
            ("plate", "Plate", "Reverb", "Пластина + High Damp.",
             ["Mix", "Decay", "High Damp", "Trail"], [("Студийный вокал/лид", "")]),
            ("spring", "Spring", "Reverb", "Пружина.",
             ["Mix", "Decay", "Tone", "Trail"], [("Surf / Fender vibe", "")]),
            ("tube-spring", "Tube Spring", "Reverb", "Ламповая пружина + Mod/Damp.",
             ["Mix", "Pre Delay", "Decay", "Low/Hi Damp", "Mod", "Trail"], [("Премиум spring", "")]),
            ("concert", "Concert", "Reverb", "Концертный зал с Mod/Damp.",
             ["Mix", "Pre Delay", "Decay", "Damp", "Mod", "Trail"], [("Большая сцена", "")]),
            ("n-star", "N-Star", "Reverb", "Яркие lush decays.",
             ["Mix", "Decay", "Trail"], [("Шиммер-свет", "")]),
            ("deepsea", "Deepsea", "Reverb", "Глубокие огромные хвосты.",
             ["Mix", "Decay", "Trail"], [("Ambient", "В миксе с барабанами — короче Decay.")]),
            ("sweet-space", "Sweet Space", "Reverb", "Модулированный сладкий space.",
             ["Mix", "Pre Delay", "Decay", "Low/High End", "Trail"], [("Пады", "")]),
            ("shimmer", "Shimmer", "Reverb", "Shimmer reverb.",
             ["Mix", "Pre Delay", "Decay", "Low/High End", "Trail"],
             [("Этно/кельт ambient", "Mix очень низкий в бэнде.")]),
        ],
    },
    "12-vol": {
        "title": "VOL — громкость",
        "chain": "Чистый уровень без окраски. Удобно на EXP как volume pedal.",
        "effects": [
            ("volume", "Volume", "Volume", "Чистый контроль уровня.",
             ["Volume"],
             [("Педаль громкости", "Назначить на EXP."),
              ("Свэллы вручную", "Перед Delay/Reverb в цепи — сдвинуть VOL ранее.")]),
        ],
    },
}


def slug_safe(s: str) -> str:
    return s


def write_effect(module_dir: Path, effect) -> None:
    slug, name, typ, desc, params, usages = effect
    d = module_dir / slug
    d.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# {name}",
        "",
        f"**Тип:** {typ}",
        "",
        "## Описание",
        "",
        desc,
        "",
        "## Параметры",
        "",
    ]
    for p in params:
        lines.append(f"- {p}")
    lines += ["", "## Варианты использования", ""]
    for title, how in usages:
        lines.append(f"### {title}")
        lines.append("")
        lines.append(how if how else "_Настройте на слух под площадку и инструмент._")
        lines.append("")
    lines += [
        "## Заметки",
        "",
        "- Имена производителей оригиналов указаны для описания звукового характера.",
        "- Следите за DSP load цепи: high-precision CAB + SnapTone + тяжёлые FX могут потребовать упрощения.",
        "",
    ]
    (d / "README.md").write_text("\n".join(lines), encoding="utf-8")


def write_module(key: str, data: dict) -> None:
    mdir = ROOT / key
    mdir.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# {data['title']}",
        "",
        data["chain"],
        "",
        "## Эффекты в модуле",
        "",
    ]
    for effect in data["effects"]:
        slug, name, typ, desc, *_ = effect
        lines.append(f"- [{name}](./{slug}/) — {typ}: {desc.split('.')[0]}.")
        write_effect(mdir, effect)
    lines += ["", "---", "", f"Всего эффектов: **{len(data['effects'])}**.", ""]
    (mdir / "README.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    index = [
        "# Модули эффектов Valeton GP-180",
        "",
        "Цепь по умолчанию:",
        "",
        "`NR → PRE → WAH → DST → N→S → AMP → CAB → EQ → MOD → DLY → RVB → VOL`",
        "",
        "Модули можно свободно менять местами. Одновременно до 12 слотов.",
        "",
        "## Список модулей",
        "",
    ]
    total = 0
    for key in sorted(MODULES.keys()):
        data = MODULES[key]
        write_module(key, data)
        n = len(data["effects"])
        total += n
        index.append(f"- [{data['title']}](./{key}/) — {n} эффект(ов)")
    index += [
        "",
        f"**Всего карточек эффектов:** {total}",
        "",
        "См. также: [NAM / SnapTone](../nam-snaptone/), [пресеты мандокастера](../presets/mandocaster/), [EQ в миксе](../eq-mix/).",
        "",
    ]
    (ROOT / "README.md").write_text("\n".join(index), encoding="utf-8")
    print(f"Generated {total} effects in {len(MODULES)} modules -> {ROOT}")


if __name__ == "__main__":
    main()
